### ISSUE TITLE
Declarative `hap deploy` configuration

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/hapistrano#105]
Hapistrano only reads deployment settings like `release-format` and `keep-release` from the CLI.

Taking into account the following configuration file:

```yaml
deploy_path: '/var/projects/my-project'
host: myserver.com
port: 2222
repo: 'https://github.com/stackbuilders/hapistrano.git'
revision: origin/master
build_script:
  - stack setup
  - stack build
restart_command: systemd restart my-app-service
```

If a user required to override the default deploy settings, needs to do that via the CLI as follows:

```sh
hap deploy -k 3 -r long -c hap.yaml
```

The current approach makes it hard to achieve reproducible builds since users have to remember to pass the same settings anytime they invoke `hap deploy`.

Hapistrano should be able to read those settings from the configuration file itself:

```yaml
deploy_path: '/var/projects/my-project'
host: myserver.com
port: 2222
repo: 'https://github.com/stackbuilders/hapistrano.git'
revision: origin/master
release_format: long
keep_releases: 3

build_script:
  - stack setup
  - stack build
restart_command: systemd restart my-app-service
```

That way hapistrano could be invoked from the CLI without passing any extra arguments:

```sh
hap deploy -c hap.yaml
```
