### ISSUE TITLE
How to deploy using a different repository?

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hapistrano#145]
I have a fork of a repository and I tried to deploy it by changing only the `repo` attribute in the yaml config file:
From:
```yaml
deploy_path: /var/projects/my-project
host: user@domain.com
repo: git@github.com:user/repository-1.git
revision: origin/master
build_script:
  - ..
```
To:
```yaml
deploy_path: /var/projects/my-project
host: user@domain.com
repo: git@github.com:user/repository-2.git
revision: origin/master
build_script:
  - ..
```
but `hap deploy -c config.yml` took the previous repo.

I supposed this happens because it always tries to clone `/var/projects/my-project/repo` into the new release:

```
[14:28:57,  2020-09-04 (-05)] INFO -- : $ git clone /var/projects/my-project/repo/ /var/projects/my-project/releases/20200904192857/
```

Is this expected? Is there a way to change or override the original repository?
