### ISSUE TITLE
Use YAML to store configuration instead of environment variables

### ISSUE THREAD

**Issue by mrkkrp** [stackbuilders/hapistrano#56]
I think there is no particular reason to use environment variables for configuration. YAML is easy to parse with the `yaml` library and I see a number of reasons to switch to it:

1. It will be handier to store the entire configuration in `hap.yaml` file and the application could load it from that file automatically so `source foo &&` part becomes unnecessary and it's easier to call `hap`.

2. We can represent collections/lists of items properly. This is actually necessary for #54, because we would like to allow to specify arbitrary files to copy, and it should be possible to copy several files/directories. How to put this into environment variables? We could use `:` or something as separator like it's done in `PATH`, but this:

   ```yaml
   deploy_path: '/var/projects/foo'
   host: myserver.com
   port: 2222
   repo: 'https://github.com/stackbuilders/hapistrano.git'
   revision: origin/master
   restart_command: echo "foo!"
   build_script:
     - stack setup
     - stack build
   copy_verbatim:
     - file-a.txt
     - file-b.txt
   ```

   is much better.

3. As shown in the example above, this allows to put the build script directly into the configuration file instead of keeping it outside. And when we specify path to build script, it's also error-prone in a sense, because it's usually a relative path and resolved path will depend on current working directory (when playing with `hap` locally I was bitten by this a couple times). YAML also handles `#` comments automatically (although it's not a problem anymore, but anyway).
