### ISSUE TITLE
Single configuration file

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/hapistrano#76]
Most of the settings across different deployment scripts such as `staging.yaml` and `production.yaml` are the same. Usually, they only differ in the name of the branch, therefore I would like to propose to use a single configuration file with different sections instead of separate files, the format might look like:

```YAML
repo: git@github.com:<org>/<repo>
build_script:
   - stack setup
   - stack build
restart_command: <restart command>

staging:
  revision: origin/master

production:
  revision: origin/production
```

Then we could change the CLI to take a section as an argument:

```
$ stack exec hap -- deploy staging
$ stack exec hap -- deploy production
``

**Comment by juanpaucar** [comment]
@sestrella Although, I'm totally aware that staging ideally should be a carbon copy of the production environment. I also think that sometimes we need flexibility and that a user may not be able to have the ideal scenario. In that sense, how would you suggest that we should handle the case when there is a difference between the necessary scripts between both. Also, it may exist the case when a project has more than one environment in continuos integration & delivery pipeline, g.e. `development -> staging -> qa -> production`. In those scenarios we would still another yaml file

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Single configuration file](https://trello.com/c/pHFYjA7z/45-single-configuration-file)

**Comment by ibarrae** [comment]
Maybe this could be achieved using TOML files @sestrella? https://kowainik.github.io/posts/2019-01-14-tomland#prefix-tree

**Comment by sestrella** [comment]
@ibarrae sorry for the late response. I would suggest start taking a look at [Dhall](https://github.com/dhall-lang/dhall-lang), perhaps? It looks promising and has [Haskell](https://github.com/dhall-lang/dhall-haskell) support. @CristhianMotoche, @DavidMazarro any thoughts?

**Comment by CristhianMotoche** [comment]
@sestrella @ibarrae Why do you want to include a new notation for the build script? Is it impossible to accomplish this only with YAML? Please, let me know your thoughts.

**Comment by DavidMazarro** [comment]
I haven't used Dhall but have known it for a while. Despite looking interesting, I think the sort of config users are doing with Hapistrano isn't complex enough to justify defaulting to Dhall (unless we want to support both languages for deployment scripts?). It might just make Hapistrano a bit harder to use for people unfamiliar with Dhall.

I would try to review if this can be done in YAML directly like @CristhianMotoche says, but I don't recall it can be done off the top of my head. In that case, TOML is a good pick IMO: it looks like it supports that feature, and is as simple/easy to use as YAML.

**Comment by CristhianMotoche** [comment]
Hey @sestrella I think we could accomplish this defining a new file version. Like some tools (e.g. CircleCI, GH Actions) do it. I think something like:

```yml
---
version: 2
repo: git@github.com:<org>/<repo>
build_script:
   - stack setup
   - stack build
restart_command: <restart command>

targets:
  - staging:
      revision: origin/master
  - production:
      revision: origin/production
```

If `version` is not given it will take the current version (let's call it `1`). Would that make sense?
